# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-31 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchanime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='path',
        ),
        migrations.AddField(
            model_name='anime',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='anime',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='anime',
            name='quality',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
